promocoes/urls.py
from django.urls import path
from . import views 


urlpatterns = [
	path('', views.home, name = 'home'),
    path('promocoes/', views.home, name='promocoes'),
	path('criar_empresa/', views.criar_empresa, name = 'criar_empresa'),
    path('criar_promocao/', views.criar_promocao, name = 'criar_promocao')
]

promofacil/urls.py
from django.contrib import admin
from django.urls import path, include
from promocoes.views import home  # Importa a função home
from django.conf.urls.static import static
from django.conf import settings
from promocoes.views import home, promofacil


urlpatterns = [
    path('', home, name = 'home'),
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('promocoes/', include('promocoes.urls')),
    path('promofacil/', promofacil, name='promofacil'),
]


if settings.DEBUG:  # Apenas durante o desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views 

urlpatterns = [
	path('login/', views.login, name='login'), 
	path('valida_login/', views.valida_login, name='valida_login'),
	path('cadastro/', views.cadastro, name='cadastro'),
	path('valida_cadastro/', views.valida_cadastro, name='valida_cadastro'),
	path('sair/', views.sair, name='sair')
]

promocoes/models.py
from django.db import models

class Promocao(models.Model):
    nome_produto = models.CharField(max_length=100)
    preco_original = models.FloatField(default=0)
    preco_promocional = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    data_inicio = models.DateField()
    data_termino = models.DateField()
    categoria = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='produtos/', null=True, blank=True)  # Armazena em media/produtos/


    def __str__(self):
        return f"{self.nome_produto}"




class Empresa(models.Model):
	nome_empresa = models.CharField(max_length=255, null=False, default="Nome da Empresa")
	email = models.EmailField(default="default@example.com")
	endereco = models.TextField(max_length=255, null=False, default="Endereço Padrão")
	telefone = models.CharField(max_length = 20, default = "")

	def __str__(self):
			# Verifique se o nome está vazio. Retorne outra informação se necessário.
			if self.nome_empresa:
				return self.nome_empresa
			elif self.email:
				return f"Empresa com email: {self.email}"
			else:
				return "Empresa sem informações"



class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

usuarios/models.py
from django.db import models


class Usuario(models.Model):
	nome = models.CharField(max_length = 30)
	email = models.EmailField()
	senha = models.CharField(max_length = 64)

	def __str__(self) -> str:
		return self.nome

promocoes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import Empresa, Promocao, Categoria

# Create your views here.
def home(request):
	categorias = Categoria.objects.all()  # Recupera todas as categorias do banco	
	empresas = Empresa.objects.all()
	promocoes = Promocao.objects.all()  # Recupera todas as promoções do banco
	return render(request, 'home.html', {'categorias': categorias, 'empresas': empresas, 'promocoes': promocoes})


def promofacil(request):
    return render(request, 'promofacil.html')  


def criar_empresa(request):
	nome_empresa = request.POST.get("nome_empresa")
	email = request.POST.get("email")
	endereco = request.POST.get("endereco")
	telefone = request.POST.get("telefone")

	empresa = Empresa(nome_empresa=nome_empresa,
					  email =email,
					  endereco=endereco,
					  telefone=telefone)
	empresa.save()
	return render(request, 'cadastroEmpresa.html')


def criar_promocao(request):
    if request.method == 'POST':
        nome_produto = request.POST.get('nome_produto')
        preco_original = request.POST.get('preco_original')
        preco_promocional = request.POST.get('preco_promocional')
        data_inicio = request.POST.get('data_inicio')
        data_termino = request.POST.get('data_termino')
        categoria = request.POST.get('categoria')
        imagem = request.FILES.get('imagem')

        # Verifique se todos os dados foram recebidos
        if not imagem:
            return HttpResponse("Erro: Imagem não foi enviada corretamente.")

        promocao = Promocao(
            nome_produto=nome_produto,
            preco_original=preco_original,
            preco_promocional=preco_promocional,
            data_inicio=data_inicio,
            data_termino=data_termino,
            categoria=categoria,
            imagem=imagem
        )
        promocao.save()
        return HttpResponse("Promoção cadastrada com sucesso!")

    return render(request, 'cadastroPromocao.html')


usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Usuario
from django.shortcuts import redirect
from hashlib import sha256

def login(request):
	status = request.GET.get('status')
	return render(request, 'login.html', {'status': status})

def cadastro(request):
	status = request.GET.get('status')
	return render(request, 'cadastro.html', {'status': status})

def valida_cadastro(request):
	nome = request.POST.get('nome')
	email = request.POST.get('email')
	senha = request.POST.get('senha')

	usuario = Usuario.objects.filter(email=email)

	if len(nome.strip()) == 0 or len(email.strip()) == 0:
		return redirect('/auth/cadastro/?status=1')

	if len(senha) < 8:
		return redirect('/auth/cadastro/?status=2')

	if len(usuario) > 0:
		return redirect('/auth/cadastro/?status=3')
	try:
		senha = sha256(senha.encode()).hexdigest()
		usuario = Usuario (nome= nome, senha = senha, email=email)
		usuario.save()
		return redirect('/auth/cadastro/?status=0')

	except:
		return redirect('/auth/cadastro/?status=4')

	
def valida_login(request):
	email = request.POST.get('email')
	senha = request.POST.get('senha')
	senha = sha256(senha.encode()).hexdigest()

	usuario = Usuario.objects.filter(email=email).filter(senha=senha)

	if len(usuario) == 0:
		return redirect('/auth/login/?status=1')
	elif len(usuario) > 0:
		request.session['usuario'] = usuario[0].id
		return redirect('/promocoes/home/')

	return HttpResponse(f"{email} {senha}")
	

def sair(request):
	request.session.flush()
	return redirect('/auth/login/')

promocoes/templates/cadastroEmpresa.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromoFácil - Cadastro</title>
    <link rel="stylesheet" href="{% static 'css/partials/cadastro/cadastro_empresa.css' %}">
    <link rel="icon" href="{% static 'img/logo_promo-facil/icone_promo.png' %}" type="image/png">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>




    <div class="container">

        
    {% if status == '0'%}
        <div class="alert alert-sucess" role="alert">
            Cadastro realizado com sucesso.
        </div>
    {% endif %}

    {% if status == '1'%}
        <div class="alert alert-danger" role="alert">
            Nome e email não podem estar vazio.
        </div>
    {% endif %}

    {% if status == '2'%}
        <div class="alert alert-danger" role="alert">
            Sua senha deve ter pelo menos 8 caracteres.
        </div>
    {% endif %}

    {% if status == '3'%}
        <div class="alert alert-danger" role="alert">
            Usuário já existe no sistema.
        </div>
    {% endif %}

    {% if status == '4'%}
        <div class="alert alert-danger" role="alert">
            Erro interno do sistema.
        </div>
    {% endif %}


        <div class="form-image">
            <img src="{% static 'img/cadastro/cadastrar_empresa.svg' %}" alt="">
        </div>

        <div class="form">

            <form method="POST" action="{% url 'criar_empresa' %}">

                {% csrf_token %}

                <div class="form-header">
                    <div class="title">
                        <h1>CADASTRAR EMPRESA</h1>
                    </div>
                    <div class="login-button">
                        <button><a href="{% url 'home' %}">Entrar</a></button>
                    </div>
                </div>

                <div class="input-group">
                    <div class="input-box">
                        <label for="nomeEmpresa">Nome da empresa</label>
                        <input class="form-control" id="nomeEmpresa" type="text" name="nome_empresa" placeholder="Digite aqui" required>
                    </div>

                    <div class="input-box">
                        <label for="adressEmpresa">Endereço da empresa</label>
                        <input class="form-control" id="adressEmpresa" type="text" name="endereco" placeholder="Digite aqui" required>
                    </div>
                    <div class="input-box">
                        <label for="email">E-mail da empresa</label>
                        <input class="form-control" id="email" type="email" name="email" placeholder="Digite aqui" required>
                    </div>

                    <div class="input-box">
                        <label for="number">Contato</label>
                        <input class="form-control" id="number" type="tel" name = "telefone" placeholder="(xx) xxxx-xxxx" required>
                    </div>
{% comment %} 
                    <div class="input-box">
                        <label for="password">Senha</label>
                        <input id="password" type="password" name="password" placeholder="Digite sua senha" required>
                    </div>


                    <div class="input-box">
                        <label for="confirmPassword">Confirme sua Senha</label>
                        <input id="confirmPassword" type="password" name="confirmPassword" placeholder="Digite sua senha novamente" required>
                    </div> {% endcomment %}

                </div>

                <div class="botoes">
                    <div class="continue-button2">
                        <a href="../../index.html"><button type="button" id="cancelarButton">Cancelar</button></a>
                    </div>
                    <div class="continue-button">
                        <a href="#"><button type="submit" id="continuarButton">Continuar</button></a>
                    </div>
                </div>

                {% comment %} <input class="bnt btn-info btn-lg" type="submit" value="Enviar"> {% endcomment %}

                
            </form>
        </div>
    </div>
</body>


    <script src="{% static '/js/script.js'%}"></script>
</body>
</html>

promocoes/templates/cadastroPromocao.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromoFácil - Cadastro_Promoção</title>
    <link rel="stylesheet" href="{% static 'css/partials/cadastro/cadastro_promocao.css' %}">
    <link rel="icon" href="{% static 'img/logo_promo-facil/icone_promo.png' %}" type="image/png">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
</head>
<body>


    <div class="container">

        
    {% if erro %}
        <div class="alert-box">
            <div class="alert alert-danger">
                {{ erro }}
            </div>
        </div>
    {% endif %}

    {% if mensagem %}
        <div class="alert-box">
            <div class="alert alert-success">
                {{ mensagem }}
            </div>
        </div>
    {% endif %}


        <div class="form-image">
            <img src="{% static 'img/cadastro/cadastro_produto.svg' %}" alt="">
        </div>

        <div class="form">

            <form method="POST" action="{% url 'criar_promocao' %} " enctype="multipart/form-data">

                {% csrf_token %}

                <div class="form-header">
                    <div class="title">
                        <h1>Cadastrar Promoção</h1>
                    </div>
                    {% comment %} <div class="login-button">
                        <button><a href="{% url 'home' %}">Entrar</a></button>
                    </div> {% endcomment %}
                </div>

                <div class="input-group">
                    <div class="input-box">
                        <label for="nomeEmpresa">Nome</label>
                        <input name = "nome_produto" class="form-control" type="text" placeholder="Nome do Produto" required>
                    </div>

                    <div class="input-box">
                        <label>Preço Original</label>
                        <input name="preco_original" class="form-control" type="number" placeholder="Preço Original" required>                        
                    </div>
                    
                    <div class="input-box">
                        <label>Preço Promocional</label>
                        <input name="preco_promocional" class="form-control" type="number" placeholder="Preço Promocional" required>
                    </div>

                
                    <div class="input-box">
                        <label>Data de Inicio</label>
                        <input name = "data_inicio" class="form-control" type="date" placeholder="Data de Inicio">
                    </div>

                    <div class="input-box">
                        <label>Data de Termino</label>
                        <input name = "data_termino" class="form-control" type="date" placeholder="Data de Termino">
                    </div>
                    
                    <div class="input-box">
                        <label>Categoria</label>
                        <select name="categoria" id="categoria" class="form-control">
                            <option value="">Selecione uma categoria</option>
                            <option value="ELETRONICO">Eletrônico</option>
                            <option value="ROUPA">Roupa</option>
                            <option value="ALIMENTO">Alimento</option>
                        </select>                    </div>
                    </div>

                    <div class="input-box">
                        <label for="imagem">Imagem do Produto</label>
                        <input type="file" name="imagem" class="form-control" required>
                    </div>
                    
                <div class="botoes">
                    <div class="continue-button2">
                        <a href="../../index.html"><button type="button" id="cancelarButton">Cancelar</button></a>
                    </div>
                    <div class="continue-button">
                        <a href="#"><button type="submit" id="continuarButton">Continuar</button></a>
                    </div>
                </div>

                {% comment %} <input class="bnt btn-info btn-lg" type="submit" value="Enviar"> {% endcomment %}

                
            </form>
        </div>
    </div>
</body>


    <script src="{% static 'js/cadastrar_produtot.js'%}"></script>
</body>
</html>

promocoes/templates/home.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromoFácil - Promoções</title>
    <link rel="stylesheet" href="{% static 'css/partials/promocoes/promocoes.css' %}">
    <link rel="icon" href="{% static 'img/logo_promo-facil/icone_promo.png' %}" type="image/png">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    

    <div class="cookie-banner" id="cookies-msg">
        <div class="cookie-text">
            <p>Utilizamos cookies para melhorar o desempenho e segurança do site, além de personalizar conteúdo e anúncios. Se desejar, você pode <a id="configCookies">configurar suas preferências</a> ou conferir nossa Política de Privacidade.</p>
            <div class="button-container">
                <button onclick="aceito()">Aceitar Cookies</button>
            </div>
        </div>
    </div>
    


    <nav class="nav-bar">

        <div class="nav-top">
            <div class="logo">
                <a href="../../index.html">
                    <img src="{% static 'img/logo_promo-facil/logo_branca__promo_facil.svg' %}">
                </a>
            </div>
    
            <div class="search-bar">
                    <i class="bx bx-search"></i>
                    <input type="search" name="pesquisar" id="search" placeholder="pesquisar">
                </form>
            </div>
    
            <div class="perfil" id="perfilLink">
            <i class="bx bxs-user" id="perfilIcon"></i>
            <div class="dropdown1" id="dropdownMenu">
                <a href="#"><i class="bx bxs-user"></i> Nome do Usuário</a>
                <a href="./gerenciar_perfil.html" id="configLink"><i class="bx bx-cog"></i> Configurações</a>
                <a href="./promocoes_user.html" id="logoutLink"><i class="bx bx-log-out"></i> Logout</a>
            </div>
        </div>
            <!-- <a href="login.html" class="btn">Login</a>  -->
        </div>

        


        <div class="nav-bottom">
            <ul>
                <li>
                    <a href="#"><i class="bx bx-menu"></i>Categorias</a>
                    <ul class="dropdown">
                        {% for categoria in categorias %}
                            <li><a href="#">{{ categoria.nome }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                
                <li>
                    <a href="#"><i class="bx bx-store"></i>Lojas</a>
                    <ul class="dropdown-store">
                        {% for empresa in empresas %}
                            <li><a href="#">{{ empresa.nome_empresa }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>



    </nav>






    <div class="carousel-container">
        <div class="carousel-slide" id="carousel-slide">
            <div class="carousel-item">
                <img src="{% static 'img/banners/Buscape_Acao_Oferta_do_Dia_V2_Desk_3640e2b163.png'%}" alt="Slide 1">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/banners/Buscape_aniversario_fast_shop_7_V1_Desk_27f4ea0ebc.png'%}" alt="Slide 2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/banners/Hero_Buscape_Prime_Day_2024_Desk_v2_7eed59d165.png'%}" alt="Slide 3">
            </div>
        </div>
        <div class="carousel-nav">
            <button id="prevBtn">&#10094;</button>
            <button id="nextBtn">&#10095;</button>
        </div>
    </div>




    
    <div class="recommended-offers-container">


        <button id="scroll-to-top" class="scroll-to-top">
            <i class="bx bx-up-arrow-alt"></i>
        </button>


        <h2>Ofertas Recomendadas</h2>
        <div class="recommended-offers">
            
            {% for promocao in promocoes %}
                <div class="offer">
                    <!-- Exemplo de imagem padrão para cada produto -->
                    <img src="{{ promocao.imagem.url }}" alt="Imagem do Produto">
                    
                    <div class="offer-details">
                        <p class="description">{{ promocao.nome_produto }}</p>
                        <p class="original-price"><del>R$ {{ promocao.preco_original }}</del></p>
                        <p class="price">R$ {{ promocao.preco_promocional }}</p>
                        <p class="store-name">{{ promocao.get_categoria_display }}</p>
                        
                        <button class="like-button">
                            <i class="bx bx-like"></i> <span class="like-count">0</span>
                        </button>
                    </div>
                </div>
            {% empty %}
                <p>Nenhuma oferta recomendada disponível no momento.</p>
            {% endfor %}
            
        </div>


    </div>

    <script src="{% static 'js/promocoes.js' %}"></script>
</body>
</html>

promocoes/templates/promofacil.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromoFácil</title>
    <link rel="icon" href="{% static 'img/logo_promo-facil/icone_promo.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/partials/index/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    
    
        <nav class="nav-bar">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'img/logo_promo-facil/logo_verde_promo_facil.svg' %}">
                </a>
            </div>

            <ul id="nav-links">
                <li class="link"><a href="{% url 'promocoes' %}">Para você</a></li>
                <li class="link"><a href="public/html/cadastro_empresa.html">Para suas vendas</a></li>
                
                <li class="link cadastro">
                    <a href="#">Cadastro

                        <span class="material-icons dropdown-icon">
                            <i class="bx bx-chevron-down"></i>
                        </span>

                    </a>
                    <ul class="drop-down">
                        <li><a href="public/html/cadastro.html">Casdastrar-se</a></li>
                        <li><a href="public/html/cadastro_empresa.html">Casdastrar empresa</a></li>
                        
                    </ul>
                </li>

                <li class="link"><a href="#footer">Sobre</a></li>
            </ul>
    
            <a href="public/html/login.html" class="btn">Login</a>    
            
            <div class="menu-icon">
                <i class="bx bx-menu" onclick="toggleMenu()"></i>
            </div>

            
        </nav>


        <header class="container">
            <div class="content">
                <span class="bluer"></span>
                <span class="bluer"></span>
                <h1>Bem-vindo ao <br>PromoFácil</h1>
                <p>Encontre as melhores promoções nos mercados locais.</p>
                <a href="public/html/promocoes.html">
                    <button class="btn2">Entrar</button>
                </a>
                
            </div>
            <div class="image">
                <img src="{% static 'img/index/homem-entregando-mantimentos-para-cliente.png' %}">
            </div>
        </header>
        





        <section class="section-carts">

            <div class="container-h1">
                <h1>Descubra ofertas locais com facilidade.</h1>
                <h1>Sem complicações</h1>
            </div>

            
            <div class="cart-container">
                

                <div class="cart">
                    <img src="{% static 'img/index/carrinho.png' %}">
                    <div class="content">
                        <p>Carrinho cheio de oportunidades</p>
                    </div>
                </div>
        
                <div class="cart">
                    <img src="{% static 'img/index/ponto_localization.png' %}">
                    <div class="content">
                        <p>Sua cesta repleta de descontos imperdíveis</p>
                    </div>
                </div>

                <div class="cart">
                    <img src="{% static 'img/index/woman_sacola.png' %}">
                    <div class="content">
                        <p>Sua cesta repleta de descontos imperdíveis</p>
                    </div>
                </div>

            </div>
        </section>



        <section class="section-image-text">
            <img src="{% static 'img/index/mao-carrinho.png' %}">
            <div class="text-content">
                <h1>Aumente suas vendas</h1>
                <h3>Destaque suas promoções aqui</h3>

                <div class="container-p">
                    <p>Você é dono de um mercado local?<br>
                        Cadastre-se na nossa plataforma para divulgar suas
                        promoções e atrair mais clientes para o seu estabelecimento.
                   
                    </p>
                </div>
                
               
                

                <button class="btn" onclick="window.location.href='public/html/cadastro_empresa.html'">Cadastre-se agora</button>
            </div>
        </section>
        






        <section class="section-cards">
            <h1>Benefícios</h1>
            <div class="cards-container">
                <div class="card">
                    <div class="gradient-rectangle"></div>
                    <h2>Economize</h2>
                    <p>Explore uma variedade de
                        promoções e descontos em
                        produtos essenciais, ajudando 
                        você a economizar tanto 
                        tempo quanto dinheiro em
                        suas compras diárias.</p>
                </div>
                <div class="card">
                    <div class="gradient-rectangle"></div>
                    <h2>Facilidade</h2>
                    <p>Navegue facilmente por ofertas
                        e promoções de mercadinhos locais
                        em um único lugar, simplificando sua
                        experiência de compra e permitindo
                        que você aproveite ao máximo as
                        oportunidades disponíveis.</p>
                </div>
                <div class="card">
                    <div class="gradient-rectangle"></div>
                    <h2>Atualizações</h2>
                    <p>Fique sempre atualizado com as
                        últimas ofertas e promoções,
                        garantindo que você nunca perca
                        uma oportunidade de economizar.</p>
                </div>
            </div>
        </section>
        



        <section class="section-image-pesquisa">

            <div class="retangulo">
                <div class="text-content">
                    <h1>Sua economia<br>começa aqui</h1>
                        <p>Encontre as melhores ofertas e promoções<br>
                            nos mercadinhos locais da sua região.
                        </p>
                </div>

                <div class="container-btn">
                    <a href="public/html/cadastro.html"><button class="btn">Cadastre-se agora</button></a>
                </div>
            </div>

            <div class="container-img">
                <img src="{% static 'img/index/Group 1.svg' %}">
            </div>
            
            

        </section>
        





        <footer id="footer" class="footer">

            <button id="scroll-to-top" class="scroll-to-top">
                <i class="bx bx-up-arrow-alt"></i>
            </button>

            <div class="image">
                <img src="{% static 'img/logo_promo-facil/logo_branca__promo_facil.svg' %}">
            </div>
            

            <div class="footer-section">
                <h3>Para você</h3>
                <ul>
                    <li><a href="#">Promoções</a></li>
                    <li><a href="#">Localização</a></li>
                    <li><a href="#">Comercios proximos</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Para seu negócio</h3>
                <ul>
                    <li><a href="#">Cadastro</a></li>
                    <li><a href="#">Consulta</a></li>
                    <li><a href="#">Localização</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Sobre</h3>
                <ul>
                    <li><a href="#">Ajuda</a></li>
                    <li><a href="#">Termos e Políticas</a></li>
                </ul>
            </div>
            <div class="footer-icons">
                <h3>Connecting</h3>
                <ul>
                    <li><a href="#"><i class="bx bxl-facebook-square"></i></a></li>
                    <li><a href="#"><i class="bx bxl-whatsapp-square"></i></a></li>
                    <li><a href="#"><i class="bx bxl-instagram-alt"></i></a></li>
                </ul>
            </div>

            <p>&copy; 2024 PromoFácil. Todos os direitos reservados.</p>
        </footer>
        


    </div>


    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/base.html
<!doctype html>
<html lang="pt-BR">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    {% block head %} {% endblock %}
    <title>{% block titulo %} {% endblock %}</title>
  </head>
  <body>
    <nav clas="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Cadastro</a>
    </nav>

    
    {% block conteudo %} {% endblock %}
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>